version: '2.0'
services:
  redis:
    image: redis:alpine
    container_name: laravel-redis

  db:
    image: mariadb:10.1
    container_name: laravel-mariadb
    working_dir: /application
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci,]
    volumes:
      - laravel-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      
  php:
    image: davidhoeck/laravel-docker-php-fpm:PHP7-apache
  # for PHP7.1 use: davidhoeck/laravel-docker-php-fpm:PHP7.1-apache
  # for PHP7.2 use: davidhoeck/laravel-docker-php-fpm:PHP7.1-apache
    container_name: laravel-php-fpm
    volumes:
      - .:/var/www/html:cached
      - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "2000:80"
    links:
     - db:db
     - redis:redis

volumes:
  laravel-database: